# Generated by Django 5.1.2 on 2024-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
    ]
