# Generated by Django 5.1.2 on 2024-11-01 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0002_cake_is_customizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecustomization',
            name='option',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
