# Generated by Django 5.1.2 on 2024-11-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0003_cakecustomization_option_order_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cake',
            new_name='cake_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='is_customizable',
        ),
        migrations.RemoveField(
            model_name='cakecustomization',
            name='option',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='available',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
    ]
