# Generated by Django 5.1.2 on 2024-11-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0004_rename_cake_cartitem_cake_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cake_id',
            new_name='cake',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='sweetspot_app.cartitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.customer'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
    ]
